# Generated by Django 5.0.7 on 2025-03-28 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_remove_submission_assignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassroom',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_classroom_students', to='faculty.classroom'),
        ),
        migrations.AlterField(
            model_name='studentclassroom',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_student_classrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
