# Generated by Django 5.0.7 on 2025-03-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_assignment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='marks',
            field=models.IntegerField(default=100),
        ),
    ]
