# Generated by Django 5.0.7 on 2025-03-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_githubsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubsubmission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubsubmission',
            name='forks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='githubsubmission',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubsubmission',
            name='repo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='githubsubmission',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
