# Generated by Django 5.0.7 on 2025-03-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_githubsubmission_description_githubsubmission_forks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubsubmission',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
