# Generated by Django 5.0.7 on 2025-03-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_githubsubmission_github_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubsubmission',
            name='github_username',
        ),
        migrations.AddField(
            model_name='githubsubmission',
            name='local_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
